[tool.poetry]
name = "youtube_scraper"
version = "0.1.0"
description = ""
authors = [
    "Akhil H Nair <aklhnrpm@gmail.com>",
]
source = [
    { name = "cobweb", url = "http://127.0.0.1:8000", default = false },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"

[tool.poetry.dependencies.pycobweb]
version = "^0.0.21"
source = "cobweb"

[tool.poetry.dev-dependencies]

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
